#!/usr/bin/env bash

if [ $(uname) == "Linux" ]; then
  echo "Installing linux packages"
  if [ $(lsb_release -si) == "Debian" ]; then
    sudo apt-get -y update
    sudo apt-get -y install git git-crypt github-hub vim tig direnv tree
  fi
fi

# If we run this on a Mac we want to setup homebrew and install everthing that is in the Brewfile
if [ $(uname) == "Darwin" ]; then
  echo "Installing darwin packages"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  curl -Lkso Brewfile https://raw.githubusercontent.com/dsteenstra/dotfiles/master/Brewfile
  brew bundle
  rm -f Brewfile
fi

echo "Installing dotfiles"
git clone --bare https://github.com/dsteenstra/dotfiles.git $HOME/.dotfiles
function dotfiles {
   $(which git) --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}
mkdir -p .dotfiles-backup
dotfiles checkout
if [ $? = 0 ]; then
  echo "Checked out dotfiles.";
  else
    echo "Backing up pre-existing dotfiles.";
    dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi;
dotfiles checkout
dotfiles config status.showUntrackedFiles no
dotfiles submodule init && dotfiles submodule update

echo "Installing vim plugins"
if [ ! -a $HOME/.vimplugindone ]; then
  vim +BundleInstall +qall
  touch $HOME/.vimplugindone
fi

echo "Installation Complete!"

exit 0
